[package]
authors = ["Spencer Burris <sburris@posteo.net>"]
categories = ["game-engines", "game-development"]
description = "Basic first-person fly camera for the Bevy game engine"
edition = "2018"
homepage = "https://github.com/sburris0/bevy_flycam/"
keywords = ["gamedev", "bevy", "3d", "camera"]
license = "ISC"
name = "bevy_flycam"
readme = "README.md"
repository = "https://github.com/sburris0/bevy_flycam/"
version = "0.5.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = {version = "0.5", default-features = false, features = ["render"]}

[dev-dependencies]
bevy = {version = "0.5", default-features = false, features = ["render", "bevy_winit", "bevy_wgpu"]}

[target.'cfg(target_os = "linux")'.dev-dependencies]
bevy = {version = "0.5", default-features = false, features = ["x11", "wayland"]}

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "scroll"
path = "examples/scroll.rs"
